# Generated by Django 3.2.4 on 2021-06-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urldata',
            old_name='slug',
            new_name='short_url',
        ),
    ]
